### ISSUE TITLE
Custom build breaks with Jammit

### ISSUE THREAD

**Issue by meleyal** [Modernizr/Modernizr#195]
I'm using [Jammit](http://documentcloud.github.com/jammit/) (with YUI compressor) for combining / minifying assets for production.

When I include a [custom build](http://modernizr.github.com/Modernizr/2.0-beta/#csstransitions-iepp) of Modernizr, the resulting packaged JS breaks.

The Firebug console just prints out the whole file highlighted in red, while Web Inspector says:

```
generic.js:24TypeError: Result of expression near '...(this,this.document)...' [[object Object]] is not a function.
```

I realize that the Modernizr build does not need compressing again, but it's very useful to have all the assets listed in one place (Jammit's `assets.yml` file), and other minified code (e.g. jQuery UI) seem to work OK.

Everything works with 1.6, or without the beta build (except my feature checks of course :)
